# Sửa chữ 'auth_db' thành tên DB bạn vừa tạo
spring.datasource.url=jdbc:postgresql://localhost:5432/ex1

# Điền đúng username của PostgreSQL (thường mặc định là postgres)
spring.datasource.username=postgres

# Điền mật khẩu mà bạn dùng để đăng nhập vào pgAdmin/PostgreSQL
spring.datasource.password=16082004
# --- CẤU HÌNH GỬI EMAIL (BẮT BUỘC ĐỂ JAVAMAILSENDER HOẠT ĐỘNG) ---
spring.mail.host=smtp.gmail.com

spring.mail.port=587
spring.mail.username=ltthien17@gmail.com
spring.mail.password=rxvuvwkobtwkehmp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.hibernate.ddl-auto=update